#!/bin/sh
folder_w=/backup
filename=$(find "$folder_w"/daily -type f -mtime +6)
now=$(date '+%d_%H:%M:%S')
#echo $filename

#basically it gradually moves backups week by week starting from the oldest, then chooses the 7days old backup from
#the daily/folder(which is supposed to have 7 backups according to the number of week days)  and puts in the last_week/

rm -rf "$folder_w"/4weeks_before/* && echo "$now 4weeks old backup removed" >> /var/log/db_backup_cron.log
mv "$folder_w"/3weeks_before/* "$folder_w"/4weeks_before/ && echo "$now 3weeks old moved to 4weeks folder" >> /var/log/db_backup_cron.log
mv "$folder_w"/week_before/* "$folder_w"/3weeks_before/ && echo "$now week_before moved to 3weeks" >> /var/log/db_backup_cron.log
mv "$folder_w"/last_week/* "$folder_w"/week_before/ && echo "$now last_week moved week_before" >> /var/log/db_backup_cron.log
mv "folder_w"/daily/"$filename" "$folder_w"/last_week/ && echo "$now oldest (last mod > 6 days) daily backup moved last_week" >> /var/log/db_backup_cron.log
rm -rf "$folder_w"/daily/* 2&>/dev/null && echo "$now cleaning daily backup folder" >> /var/log/db_backup_cron.log

#the backup folder structure looks like
# root: hourly/ daily/ last_week/ week_before/ 3weeks_before/ 4weeks_before/
