#!/bin/sh
#DO NOT FORGET!!! TO set the database-name, backupPATH and mpass(mariadb oneadmin user password) and  muser(user for databse backup) variables accordingly
NOW=$(date '+%d_%H:%M:%S')
GZIP=$(which gzip)
MYSQLDUMP=$(which mysqldump)
### MySQL Server Login info ###
MHOST=127.0.0.1
MUSER=oneadmin
BFOLD=/backup/daily
DFOLD=/backup/hourly
DATABASE=opennebula
$MYSQLDUMP -h $MHOST -u $MUSER --log-error=/var/log/mariadb/mdbdump.log --databases $DATABASE | $GZIP -9 > $BFOLD/sqldump-$NOW.sql.gz && echo "$now daily backup has finished" >> /var/log/db_backup_cron.log 
rm -rf "$DFOLD"/* && echo "$now hourly backup folder has been cleaned" >> /var/log/db_backup_cron.log
